/*******************************************************************************
 * Copyright (c) 2013-2016 LAAS-CNRS (www.laas.fr)
 * 7 Colonel Roche 31077 Toulouse - France
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Initial Contributors:
 *     Thierry Monteil : Project manager, technical co-manager
 *     Mahdi Ben Alaya : Technical co-manager
 *     Samir Medjiah : Technical co-manager
 *     Khalil Drira : Strategy expert
 *     Guillaume Garzone : Developer
 *     François Aïssaoui : Developer
 *
 * New contributors :
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.15 at 03:56:27 PM CEST 
//

package org.eclipse.om2m.commons.resource;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

import org.eclipse.om2m.commons.constants.ShortName;
import org.eclipse.om2m.commons.resource.flexcontainerspec.ActivateClockTimerFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.AlarmSensorFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.AlarmSpeakerFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.AtmosphericPressureSensorFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.AudioVideoInputFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.AudioVolumeFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.BatteryFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.BinarySwitchFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.BioElectricalImpedanceAnalysisFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.BoilerFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.BrewingFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.BrightnessFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.ClockFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.ColourFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.ColourSaturationFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.ContactSensorFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.DeactivateClockTimerFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.DecrementNumberValueFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.DeviceAirConditionerFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.DeviceCameraFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.DeviceClothesWasherFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.DeviceCoffeeMachineFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.DeviceContactDetectorFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.DeviceDoorFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.DeviceElectricVehicleChargerFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.DeviceFloodDetectorFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.DeviceGasValveFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.DeviceLightFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.DeviceMicrogenerationFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.DeviceMotionDetectorFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.DeviceNumberDeviceFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.DeviceOvenFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.DeviceRefrigeratorFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.DeviceRobotCleanerFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.DeviceSmartElectricMeterFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.DeviceSmokeDetectorFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.DeviceSmokeExtractorFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.DeviceStorageBatteryFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.DeviceSwitchButtonFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.DeviceTelevisionFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.DeviceTemperatureDetectorFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.DeviceThermostatFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.DeviceWarningDeviceFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.DeviceWaterHeaterFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.DeviceWaterValveFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.DeviceWeatherStationFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.DoorStatusFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.DownChannelFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.DownVolumeFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.ElectricVehicleConnectorFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.EnergyConsumptionFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.EnergyGenerationFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.ExtendedCarbonDioxideSensorFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.FaultDetectionFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.FoamingFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.GrinderFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.HeightFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.HotWaterSupplyFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.IncrementNumberValueFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.KeepWarmFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.KeypadFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.LiquidLevelFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.LockFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.MotionSensorFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.NoiseFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.NumberValueFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.OximeterFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.PersonSensorFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.PowerSaveFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.PushButtonFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.RecorderFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.RefrigerationFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.RelativeHumidityFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.ResetNumberValueFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.RinseLevelFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.RunModeFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.SignalStrengthFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.SmokeSensorFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.SpinLevelFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.StreamingFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.TelevisionChannelFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.TemperatureAlarmFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.TemperatureFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.TimerFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.ToggleFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.TurboFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.UpChannelFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.UpVolumeFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.WaterFlowFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.WaterLevelFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.WaterSensorFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.WeightFlexContainerAnnc;
import org.eclipse.om2m.commons.resource.flexcontainerspec.WindFlexContainerAnnc;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.onem2m.org/xml/protocols}announcedResource">
 *       &lt;sequence>
 *         &lt;element name="appName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="App-ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AE-ID" type="{http://www.onem2m.org/xml/protocols}ID"/>
 *         &lt;element name="pointOfAccess" type="{http://www.onem2m.org/xml/protocols}pOAList" minOccurs="0"/>
 *         &lt;element name="ontologyRef" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="nodeLink" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element name="childResource" type="{http://www.onem2m.org/xml/protocols}childResourceRef" maxOccurs="unbounded"/>
 *           &lt;choice maxOccurs="unbounded">
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}container"/>
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}containerAnnc"/>
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}group"/>
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}groupAnnc"/>
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}accessControlPolicy"/>
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}accessControlPolicyAnnc"/>
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}subscription"/>
 *             &lt;element ref="{http://www.onem2m.org/xml/protocols}pollingChannel"/>
 *           &lt;/choice>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = ShortName.AEA)
public class AEAnnc extends AnnouncedResource {
	
	@XmlElement(name = ShortName.APP_NAME, required=false, namespace="")
	protected String appName;
	
	@XmlElement(name = ShortName.APP_ID, required = false, namespace="")
	protected String appID;
	
	@XmlElement(name = ShortName.AE_ID, required = false, namespace="")
	protected String aeid;
	
	@XmlList
	@XmlElement(name = ShortName.POA, required=false, namespace="")
	protected List<String> pointOfAccess;
	
	@XmlSchemaType(name = "anyURI")
	@XmlElement(name = ShortName.ONTOLOGY_REF, required=false, namespace="")
	protected String ontologyRef;
	
	@XmlSchemaType(name = "anyURI")
	@XmlElement(name = ShortName.NODE_LINK, required=false, namespace="")
	protected String nodeLink;
	
	@XmlElement(name = ShortName.CHILD_RESOURCE, namespace="")
	protected List<ChildResourceRef> childResource;
	
	@XmlElements({
		@XmlElement(name = ShortName.CNT, namespace = "http://www.onem2m.org/xml/protocols", type = Container.class),
		@XmlElement(name = ShortName.CNTA, namespace = "http://www.onem2m.org/xml/protocols", type = ContainerAnnc.class),
		@XmlElement(name = ShortName.GROUP, namespace = "http://www.onem2m.org/xml/protocols", type = Group.class),
		@XmlElement(name = ShortName.GROUPA, namespace = "http://www.onem2m.org/xml/protocols", type = GroupAnnc.class),
		@XmlElement(name = ShortName.ACP, namespace = "http://www.onem2m.org/xml/protocols", type = AccessControlPolicy.class),
		@XmlElement(name = ShortName.ACPA, namespace = "http://www.onem2m.org/xml/protocols", type = AccessControlPolicyAnnc.class),
		@XmlElement(name = ShortName.SUB, namespace = "http://www.onem2m.org/xml/protocols", type = Subscription.class),
		@XmlElement(name = ShortName.PCH, namespace = "http://www.onem2m.org/xml/protocols", type = PollingChannel.class),
		@XmlElement(name = ShortName.FCNTA, namespace = "http://www.onem2m.org/xml/protocols", type = AbstractFlexContainerAnnc.class),
		@XmlElement(name = AlarmSpeakerFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = AlarmSpeakerFlexContainerAnnc.class),
		@XmlElement(name = AudioVideoInputFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = AudioVideoInputFlexContainerAnnc.class),
		@XmlElement(name = AudioVolumeFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = AudioVolumeFlexContainerAnnc.class),
		@XmlElement(name = UpVolumeFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = UpVolumeFlexContainerAnnc.class),
		@XmlElement(name = DownVolumeFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = DownVolumeFlexContainerAnnc.class),
		@XmlElement(name = BatteryFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = BatteryFlexContainerAnnc.class),
		@XmlElement(name = BinarySwitchFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = BinarySwitchFlexContainerAnnc.class),
		@XmlElement(name = ToggleFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = ToggleFlexContainerAnnc.class),
		@XmlElement(name = BioElectricalImpedanceAnalysisFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = BioElectricalImpedanceAnalysisFlexContainerAnnc.class),
		@XmlElement(name = BoilerFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = BoilerFlexContainerAnnc.class),
		@XmlElement(name = BrightnessFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = BrightnessFlexContainerAnnc.class),
		@XmlElement(name = ClockFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = ClockFlexContainerAnnc.class),
		@XmlElement(name = ColourFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = ColourFlexContainerAnnc.class),
		@XmlElement(name = ColourSaturationFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = ColourSaturationFlexContainerAnnc.class),
		@XmlElement(name = DoorStatusFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = DoorStatusFlexContainerAnnc.class),
		@XmlElement(name = ElectricVehicleConnectorFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = ElectricVehicleConnectorFlexContainerAnnc.class),
		@XmlElement(name = EnergyConsumptionFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = EnergyConsumptionFlexContainerAnnc.class),
		@XmlElement(name = EnergyGenerationFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = EnergyGenerationFlexContainerAnnc.class),
		@XmlElement(name = FaultDetectionFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = FaultDetectionFlexContainerAnnc.class),
		@XmlElement(name = HeightFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = HeightFlexContainerAnnc.class),
		@XmlElement(name = HotWaterSupplyFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = HotWaterSupplyFlexContainerAnnc.class),
		@XmlElement(name = KeypadFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = KeypadFlexContainerAnnc.class),
		@XmlElement(name = MotionSensorFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = MotionSensorFlexContainerAnnc.class),
		@XmlElement(name = OximeterFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = OximeterFlexContainerAnnc.class),
		@XmlElement(name = PowerSaveFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = PowerSaveFlexContainerAnnc.class),
		@XmlElement(name = PushButtonFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = PushButtonFlexContainerAnnc.class),
		@XmlElement(name = RecorderFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = RecorderFlexContainerAnnc.class),
		@XmlElement(name = RefrigerationFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = RefrigerationFlexContainerAnnc.class),
		@XmlElement(name = RelativeHumidityFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = RelativeHumidityFlexContainerAnnc.class),
		@XmlElement(name = RinseLevelFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = RinseLevelFlexContainerAnnc.class),
		@XmlElement(name = RunModeFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = RunModeFlexContainerAnnc.class),
		@XmlElement(name = SignalStrengthFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = SignalStrengthFlexContainerAnnc.class),
		@XmlElement(name = SmokeSensorFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = SmokeSensorFlexContainerAnnc.class),
		@XmlElement(name = SpinLevelFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = SpinLevelFlexContainerAnnc.class),
		@XmlElement(name = TelevisionChannelFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = TelevisionChannelFlexContainerAnnc.class),
		@XmlElement(name = UpChannelFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = UpChannelFlexContainerAnnc.class),
		@XmlElement(name = DownChannelFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = DownChannelFlexContainerAnnc.class),
		@XmlElement(name = TemperatureFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = TemperatureFlexContainerAnnc.class),
		@XmlElement(name = TemperatureAlarmFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = TemperatureAlarmFlexContainerAnnc.class),
		@XmlElement(name = TimerFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = TimerFlexContainerAnnc.class),
		@XmlElement(name = ActivateClockTimerFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = ActivateClockTimerFlexContainerAnnc.class),
		@XmlElement(name = DeactivateClockTimerFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = DeactivateClockTimerFlexContainerAnnc.class),
		@XmlElement(name = TurboFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = TurboFlexContainerAnnc.class),
		@XmlElement(name = WaterFlowFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = WaterFlowFlexContainerAnnc.class),
		@XmlElement(name = WaterLevelFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = WaterLevelFlexContainerAnnc.class),
		@XmlElement(name = WaterSensorFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = WaterSensorFlexContainerAnnc.class),
		@XmlElement(name = WeightFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = WeightFlexContainerAnnc.class),
		@XmlElement(name = WindFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = WindFlexContainerAnnc.class),
		@XmlElement(name = StreamingFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = StreamingFlexContainerAnnc.class),
		@XmlElement(name = PersonSensorFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = PersonSensorFlexContainerAnnc.class),
		@XmlElement(name = BrewingFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = BrewingFlexContainerAnnc.class),
		@XmlElement(name = LiquidLevelFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = LiquidLevelFlexContainerAnnc.class),
		@XmlElement(name = GrinderFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = GrinderFlexContainerAnnc.class),
		@XmlElement(name = FoamingFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = FoamingFlexContainerAnnc.class),
		@XmlElement(name = KeepWarmFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = KeepWarmFlexContainerAnnc.class),
		@XmlElement(name = ContactSensorFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = ContactSensorFlexContainerAnnc.class),
		@XmlElement(name = AlarmSensorFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = AlarmSensorFlexContainerAnnc.class),
		@XmlElement(name = LockFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = LockFlexContainerAnnc.class),
		@XmlElement(name = AtmosphericPressureSensorFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = AtmosphericPressureSensorFlexContainerAnnc.class),
		@XmlElement(name = NoiseFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = NoiseFlexContainerAnnc.class),
		@XmlElement(name = ExtendedCarbonDioxideSensorFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = ExtendedCarbonDioxideSensorFlexContainerAnnc.class),
		@XmlElement(name = NumberValueFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = NumberValueFlexContainerAnnc.class),
		@XmlElement(name = DecrementNumberValueFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = DecrementNumberValueFlexContainerAnnc.class),
		@XmlElement(name = IncrementNumberValueFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = IncrementNumberValueFlexContainerAnnc.class),
		@XmlElement(name = ResetNumberValueFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = ResetNumberValueFlexContainerAnnc.class),
		@XmlElement(name = DeviceAirConditionerFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = DeviceAirConditionerFlexContainerAnnc.class),
		@XmlElement(name = DeviceClothesWasherFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = DeviceClothesWasherFlexContainerAnnc.class),
		@XmlElement(name = DeviceElectricVehicleChargerFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = DeviceElectricVehicleChargerFlexContainerAnnc.class),
		@XmlElement(name = DeviceLightFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = DeviceLightFlexContainerAnnc.class),
		@XmlElement(name = DeviceMicrogenerationFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = DeviceMicrogenerationFlexContainerAnnc.class),
		@XmlElement(name = DeviceOvenFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = DeviceOvenFlexContainerAnnc.class),
		@XmlElement(name = DeviceRefrigeratorFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = DeviceRefrigeratorFlexContainerAnnc.class),
		@XmlElement(name = DeviceRobotCleanerFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = DeviceRobotCleanerFlexContainerAnnc.class),
		@XmlElement(name = DeviceSmartElectricMeterFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = DeviceSmartElectricMeterFlexContainerAnnc.class),
		@XmlElement(name = DeviceStorageBatteryFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = DeviceStorageBatteryFlexContainerAnnc.class),
		@XmlElement(name = DeviceTelevisionFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = DeviceTelevisionFlexContainerAnnc.class),
		@XmlElement(name = DeviceThermostatFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = DeviceThermostatFlexContainerAnnc.class),
		@XmlElement(name = DeviceWaterHeaterFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = DeviceWaterHeaterFlexContainerAnnc.class),
		@XmlElement(name = DeviceCameraFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = DeviceCameraFlexContainerAnnc.class),
		@XmlElement(name = DeviceCoffeeMachineFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = DeviceCoffeeMachineFlexContainerAnnc.class),
		@XmlElement(name = DeviceContactDetectorFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = DeviceContactDetectorFlexContainerAnnc.class),
		@XmlElement(name = DeviceDoorFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = DeviceDoorFlexContainerAnnc.class),
		@XmlElement(name = DeviceFloodDetectorFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = DeviceFloodDetectorFlexContainerAnnc.class),
		@XmlElement(name = DeviceGasValveFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = DeviceGasValveFlexContainerAnnc.class),
		@XmlElement(name = DeviceMotionDetectorFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = DeviceMotionDetectorFlexContainerAnnc.class),
		@XmlElement(name = DeviceSmokeDetectorFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = DeviceSmokeDetectorFlexContainerAnnc.class),
		@XmlElement(name = DeviceSmokeExtractorFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = DeviceSmokeExtractorFlexContainerAnnc.class),
		@XmlElement(name = DeviceSwitchButtonFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = DeviceSwitchButtonFlexContainerAnnc.class),
		@XmlElement(name = DeviceTemperatureDetectorFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = DeviceTemperatureDetectorFlexContainerAnnc.class),
		@XmlElement(name = DeviceWarningDeviceFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = DeviceWarningDeviceFlexContainerAnnc.class),
		@XmlElement(name = DeviceWaterValveFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = DeviceWaterValveFlexContainerAnnc.class),
		@XmlElement(name = DeviceWeatherStationFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = DeviceWeatherStationFlexContainerAnnc.class),
		@XmlElement(name = DeviceNumberDeviceFlexContainerAnnc.SHORT_NAME, namespace="http://www.onem2m.org/xml/protocols/homedomain", type = DeviceNumberDeviceFlexContainerAnnc.class)
	})
	protected List<Resource> containerOrContainerAnncOrGroup;

	/**
	 * Gets the value of the appName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAppName() {
		return appName;
	}

	/**
	 * Sets the value of the appName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setAppName(String value) {
		this.appName = value;
	}

	/**
	 * Gets the value of the appID property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAppID() {
		return appID;
	}

	/**
	 * Sets the value of the appID property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setAppID(String value) {
		this.appID = value;
	}

	/**
	 * Gets the value of the aeid property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAEID() {
		return aeid;
	}

	/**
	 * Sets the value of the aeid property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setAEID(String value) {
		this.aeid = value;
	}

	/**
	 * Gets the value of the pointOfAccess property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the pointOfAccess property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getPointOfAccess().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link String }
	 * 
	 * 
	 */
	public List<String> getPointOfAccess() {
		if (pointOfAccess == null) {
			pointOfAccess = new ArrayList<String>();
		}
		return this.pointOfAccess;
	}

	/**
	 * Gets the value of the ontologyRef property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getOntologyRef() {
		return ontologyRef;
	}

	/**
	 * Sets the value of the ontologyRef property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setOntologyRef(String value) {
		this.ontologyRef = value;
	}

	/**
	 * Gets the value of the nodeLink property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getNodeLink() {
		return nodeLink;
	}

	/**
	 * Sets the value of the nodeLink property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setNodeLink(String value) {
		this.nodeLink = value;
	}

	/**
	 * Gets the value of the childResource property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the childResource property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getChildResource().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link ChildResourceRef }
	 * 
	 * 
	 */
	public List<ChildResourceRef> getChildResource() {
		if (childResource == null) {
			childResource = new ArrayList<ChildResourceRef>();
		}
		return this.childResource;
	}

	/**
	 * Gets the value of the containerOrContainerAnncOrGroup property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the containerOrContainerAnncOrGroup property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getContainerOrContainerAnncOrGroup().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link Container } {@link ContainerAnnc } {@link Group } {@link GroupAnnc }
	 * {@link AccessControlPolicy } {@link AccessControlPolicyAnnc }
	 * {@link Subscription } {@link PollingChannel }
	 * 
	 * 
	 */
	public List<Resource> getContainerOrContainerAnncOrGroup() {
		if (containerOrContainerAnncOrGroup == null) {
			containerOrContainerAnncOrGroup = new ArrayList<Resource>();
		}
		return this.containerOrContainerAnncOrGroup;
	}

}
